name: checks
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  safety:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Forbid secrets
        run: bash bootstrap/checks/forbid-secrets.sh

      - name: Shellcheck
        run: |
          sudo apt-get update -y && sudo apt-get install -y shellcheck
          bash bootstrap/checks/shellcheck.sh
