#!/usr/bin/env bash
# line-budget — authored tracked lines at a ref, and the delta against the
# baseline the budget rule was written at (docs/plans/PRIME_FLEET_AUTHORING_PLAN.md §4).
#
# A budget with no single agreed measurement is not a constraint, it is a mood:
# the first two figures quoted in this program disagreed by ~1400 lines purely
# because one included generated lockfiles and a different window. The metric is
# defined HERE, once, so a delta is a fact rather than a method.
#
# Excluded, and why: .claude/ is gitignored dev tooling and not the product;
# *-lock.json is generated by npm and moves on unrelated installs; binary and
# vendored assets have no meaningful line count.
#
#   scripts/line-budget.sh            delta for HEAD
#   scripts/line-budget.sh <ref>      delta for a ref
#   scripts/line-budget.sh --series   every commit since the baseline
set -euo pipefail

BASELINE="${LINE_BUDGET_BASELINE:-474d7fd}"

count() {
  git grep -I -c '' "$1" -- \
    ':!.claude/**' ':!**/package-lock.json' ':!package-lock.json' \
    ':!**/*.svg' ':!**/*.png' ':!**/*.ico' ':!**/*.woff' ':!**/*.woff2' \
    2>/dev/null | awk -F: '{s+=$NF} END {print s+0}'
}

base="$(count "$BASELINE")"

report() {
  local ref="$1" n
  n="$(count "$ref")"
  printf '%-9s %7d %+6d  %s\n' \
    "$(git rev-parse --short "$ref")" "$n" "$((n - base))" \
    "$(git log -1 --format=%s "$ref" | cut -c1-58)"
}

printf '%-9s %7s %6s  %s\n' commit lines delta subject
printf '%-9s %7d %6s  %s\n' "$(git rev-parse --short "$BASELINE")" "$base" base 'BASELINE — the commit that wrote the rule'

if [[ "${1:-}" == "--series" ]]; then
  for c in $(git log --format=%H "$BASELINE..HEAD" | tac); do report "$c"; done
else
  report "${1:-HEAD}"
fi
